version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/build"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[pip]"

  - package-ecosystem: "docker"
    directory: "/build"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[docker] "
