version: '3.8'

x-common-environment: &common-environment
  LLM_CONTAINER_NAME: "gpu-llm-1"
  DATABASE_CONN_STRING: "postgresql://postgres:postgres@db:5432/main_app"
  POSTGRES_PASSWORD: postgres
  POSTGRES_USER: postgres
  POSTGRES_DB: main_app
  QDRANT_HOST: http://vector_db:6333
  LLM_HOST: http://llm:11434

x-common-networks: &common-networks
  - main_network

services:
  main_app:
   # build:
    #   context: ../..
    #   dockerfile: build/Dockerfile
    image: kurdzik/chat-with-documents:latest
    ports:
      - "80:8501"
    environment:
      <<: *common-environment
      K8S_DEPLOYMENT: "False"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - vector_db
      - db
      - llm
    networks: *common-networks

  vector_db:
    image: qdrant/qdrant:latest
    ports:
      - "6330:6333"
    networks: *common-networks

  db:
    image: postgres:latest
    restart: always
    environment: *common-environment
    networks: *common-networks

  llm:
    image: ollama/ollama:latest
    networks: *common-networks
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  # api:
  #   image: kurdzik/chat-with-documents-api:latest
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     <<: *common-environment

  #   depends_on:
  #     - db
  #     - llm
  #     - vector_db
  #   networks: *common-networks

  langfuse-server:
    image: ghcr.io/langfuse/langfuse:latest
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://postgres:postgres@db:5432/main_app
      NEXTAUTH_SECRET: mysecret
      SALT: mysalt
      NEXTAUTH_URL: http://localhost:3000
      TELEMETRY_ENABLED: ${TELEMETRY_ENABLED:-true}
      NEXT_PUBLIC_SIGN_UP_DISABLED: ${NEXT_PUBLIC_SIGN_UP_DISABLED:-false}
      LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES: ${LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES:-false}
    networks: *common-networks

networks:
  main_network:
