version: '3.8'

services:
  main_app:
    build:
      context: ..
      dockerfile: build/Dockerfile
    ports:
      - "80:8501"
    environment:
      OPENAI_APIKEY: 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
      QDRANT_HOST: http://vector_db:6333
      DATABASE_HOST: http://app_db:5432
      K8S_DEPLOYMENT: False
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: main_app

    depends_on:
      - vector_db
      - db
    networks:
      - main_network

  vector_db:
    image: qdrant/qdrant:latest
    networks:
      - main_network

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: main_app
    networks:
      - main_network

networks:
  main_network:
