name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed

jobs:
  build:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: shellcheck
        uses: ludeeus/action-shellcheck@1.1.0
        with:
          severity: error
          scandir: './'
          format: tty

      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build and push
        run: make TAG=$VERSION

      - name: build and push latest
        run: make TAG=latest
