name: Build and Deploy

env:
  VERSION: 0.2.1

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed

jobs:
  build:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        run: |
          docker build -t kurdzik/chat-with-documents -f build/Dockerfile .
          docker tag kurdzik/chat-with-documents kurdzik/chat-with-documents:${{ env.VERSION}}
          docker push kurdzik/chat-with-documents:${{ env.VERSION}}
      - name: Build and push latest
        run: |
          docker build -t kurdzik/chat-with-documents -f build/Dockerfile .
          docker tag kurdzik/chat-with-documents kurdzik/chat-with-documents:latest
          docker push kurdzik/chat-with-documents:latest
