name: CI/CD

env:
  VERSION: 0.5.0

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed

jobs:
  build:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: shellcheck
        uses: ludeeus/action-shellcheck@1.1.0
        with:
          severity: error
          scandir: './'
          format: tty

      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        run: |
          docker build -t kurdzik/chat-with-documents -f build/Dockerfile .
          docker push kurdzik/chat-with-documents:${{ env.VERSION}}
      - name: Build and push latest
        run: |
          docker build -t kurdzik/chat-with-documents -f build/Dockerfile .
          docker push kurdzik/chat-with-documents:latest
